### ISSUE TITLE
WatchCloudAdmin Crash

### ISSUE THREAD

**Issue by moh1122** [bogdandovgopol/WatchCloud#4]
Hello
im really interested in this proj but its crashing while running WatchCloudAdmin with error "Could not find a storyboard named Auth in Bundle"
Any clue?
Thank you

**Comment by bogdandovgopol** [comment]
Hi,

There was an issue with memberships. I've updated the project, should be ok now. 

List of files where you have to update target membership to make it work:
WatchCloud/Storyboards/Auth.storyboard
WatchCloud/LoginVC.swift
WatchCloud/XIBs/ForgotPasswordVC.swift
WatchCloud/XIBs/ForgotPasswordVC.xib

![image](https://user-images.githubusercontent.com/30866972/61993568-18021380-b0b1-11e9-9238-549871950998.png)
